#!/bin/zsh

# This script delete unused packages. Be vigilant and read carefully what he wants to remove

sudo dnf rm ImageMagick\* \
NetworkManager-openconnect-gnome \
NetworkManager-openvpn-gnome \
NetworkManager-pptp-gnome \
NetworkManager-ssh-gnome \
NetworkManager-vpnc-gnome \
abrt \
adcli \
baobab \
brltty \
cheese \
chrome-gnome-shell \
gnome-browser-connector \
cyrus-sasl-gssapi \
cyrus-sasl-plain \
dos2unix \
eog \
f41-backgrounds-gnome \
fedora-bookmarks \
fedora-chromium-config \
fedora-flathub-remote \
fedora-workstation-backgrounds \
firefox \
geolite2\* \
gnome-backgrounds \
gnome-boxes \
gnome-characters \
gnome-classic\* \
gnome-clocks \
gnome-color-manager \
gnome-contacts \
gnome-disk-utility \
gnome-font-viewer \
gnome-logs \
gnome-maps \
gnome-remote-desktop \
gnome-screenshot \
gnome-themes-extra \
gnome-tour \
gnome-user\* \
gnome-weather \
hyperv\* \
ibus-hangul \
ibus-typing-booster \
kpartx \
libreoffice\* \
livesys-scripts \
lvm2 \
mediawriter \
mlocate \
mozilla-filesystem \
mtr \
net-snmp-libs \
net-tools \
nfs-utils \
nmap-ncat \
nm-connection-editor \
openssh-server \
open-vm\* \
podman\* \
ppp\* \
qadwaitadecorations-qt5 \
qemu-guest-agent \
quota \
quota-devel \
realmd \
rhythmbox \
rng-tools \
rsync \
sane-airscan \
sgpio \
simple-scan \
sos \
gnome-connections \
gnome-system-monitor \
snapshot \
speech\* \
spice-vdagent \
sssd\* \
tcpdump \
teamd \
thermald \
totem \
traceroute \
virtualbox-guest-additions \
words \
xorg-x11-drv-amdgpu \
xorg-x11-drv-vmware \
yajl \
evince\* \
hangul\* \
kkc\* \
libvirt\* \
m17n\* \
pinyin\* \
yelp\* \
zhuyin\*
