#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-D-0 -d I II III IV

#### BSPWM configuration ####
# bspc config border_radius                45
bspc config window_gap 			  10
bspc config top_padding 25
bspc config top_monocle_padding 	  0
bspc config border_width 		  0
bspc config bottom_padding                25
bspc config left_padding                  50
bspc config right_padding                 50
bspc config single_monocle                true
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_by_distance             true
bspc config paddingless_monocle  	  true
bspc config focus_follows_pointer         true
bspc config ignore_ewmh_focus 		  true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Colors
bspc config active_border_color \#665c54
bspc config focused_border_color \#665c54
bspc config normal_border_color \#363836

# Rules
bspc rule -a Rofi state=floating follow=on center=true 
#bspc rule -a Lxappearance state=floating follow=on center=false
bspc desktop -f 1

# AUTOSTART
sh /home/georgybog/.config/scripts/feh_bing_wallpaper.sh
sh /home/georgybog/.config/polybar/launch.sh &
dunst_run &
sh /home/georgybog/.config/picom/picom.sh &

setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle
